src/goods/urls.py
from django.urls import path, include
from . import views

app_name = 'goods'

urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:cat_slug>/', views.index, name='view_category'),
    path('product/<slug:slug>/', views.product_details, name='product_details'),
]

src/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('about/', views.about, name='about')
]

src/tech_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from tech_shop import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('main.urls', namespace='main')),
    path('', include('goods.urls', namespace='goods')),
    path('api/', include('goods.api.urls', namespace='goods_api')),
    path('users/', include('users.urls', namespace='users')),
    path('carts/', include('carts.urls', namespace='carts')),
    path('api/carts/', include('carts.api.urls', namespace='carts_api')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('api/orders/', include('orders.api.urls', namespace='orders_api')),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
        ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views


app_name = "users"

urlpatterns = [
    path("register/", views.register_user, name="register"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name='users/password_reset.html',
            success_url=reverse_lazy("users:password_reset_done"),
            email_template_name="users/password_reset_email.html",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done",
        auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy("users:password_reset_complete")
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done",
        auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name="password_reset_complete",
    ),
]

src/templates/base.html
{% load static %}
{% load goods_tags %}
{% load carts_tags %}

{% get_cart request as goods %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}

      {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="{% static "js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static 'js/jquery-ajax.js' %}"></script>
    <div class="message-container">
      {% if messages %}
        {% for message in messages %}
        {% if message.tags == 'error' %}
          <div class="alert alert-danger alert-dismissible message" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% else %}
        <div class="alert alert-{{ message.tags }} alert-dismissible message" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}
      </div>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" id="nav">
        <div class="container-fluid container">
          <a class="navbar-brand" href="{% url 'goods:index' %}">TECH SHOP</a>
          <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="navbar-collapse collapse" id="navbarCollapse" style="">
          <ul class="navbar-nav me-auto mb-md-0">
            <li class="nav-item" style='display: flex; align-items: center; margin-right: 7px;'>
              <ul class="navbar-nav">
                {% block catalog %}
                <li class="nav-item dropdown">
                  <a class="nav-link active dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="padding: 0;">
                    Каталог
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                    <li><a class='dropdown-item' href="{% url 'goods:index' %}">Всі товари</a></li>
                  {% get_categories as categories %}
                  {% for category in categories %}
                  <li><a class='dropdown-item' href="{% url 'goods:view_category' category.slug %}">{{ category.name }}</a></li>
                  {% endfor %}
                </ul>
                {% endblock  %}
              </ul>
            </li>
            {% block cart_nav %}
            <li class="nav-item">
              <a class="nav-link active" id="cart-nav" data-bs-toggle="modal" data-bs-target="#exampleModal">
                <img src="{% static 'goods/cart.svg' %}" style='width: 20px;'>
                <span id='goods-in-cart-count'>{{ goods.total_quantity }}</span>
              </a>
            </li>
            {% endblock  %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'main:about' %}">Про нас</a>
            </li>
          </ul>
          <form class="d-flex" role="search" action="{% url "goods:index" %}">
            <input class="form-control me-2" type="search" placeholder="Я шукаю..." aria-label="Search" name="q" />
          </form>
          <div class="d-flex">
            {% if user.is_authenticated %}
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" 
                data-bs-toggle="dropdown" aria-expanded="false" style="padding: 0; margin: 5px 0;">
                  {% if user.image %}
                  <img src="{{ user.image.url }}" alt="{{ user.username }}" class='mini-profile-pic'>
                  {% else %}
                  <img src="{% static 'users/default-avatar-profile.jpg' %}" alt="default user photo" class='mini-profile-pic'>
                  {% endif %}
                </a>
                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                  <li><a class="dropdown-item" href="{% url "users:profile" %}">Профіль</a></li>
                  <li><a class="dropdown-item" href="{% url "users:logout" %}">Вийти</a></li>
                </ul>
              </ul>
            </li>
            {% else %}
            <a type="button" class="btn btn-outline-light me-2" href="{% url "users:login" %}">Увійти</a>
            <a type="button" class="btn btn-warning" href="{% url "users:register" %}">Зареєструватися</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    

    {% block cart_modal %}
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Кошик</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body" id="cart-items-container">
            {% include 'carts/includes/cart.html' %}
          </div>
        </div>
      </div>
    </div>
    {% endblock  %}

    
    <div class="wrapper">
      <div class="container content">
        {% block content %}
        
        {% endblock %}
      </div>
      <div class="container mt-4" id="footer">
        <footer class="py-3">
          <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item">
              <a href="{% url 'goods:index' %}" class="nav-link px-2 text-body-secondary">TECH SHOP</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'main:about' %}" class="nav-link px-2 text-body-secondary">Про нас</a>
            </li>
            <li class="nav-item">
              <a href="{% url "users:profile" %}" class="nav-link px-2 text-body-secondary">Профіль</a>
            </li>
          </ul>
          <p class="text-center text-body-secondary">© 2024 TECH SHOP, Inc</p>
        </footer>
      </div>
    </div>
  </body>
</html>

src/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}TECH SHOP{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static "css/style.css" %}">
    </head>
    <body>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <header class="p-3 text-bg-dark">
            <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
                </a>
        
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'index' %}" class="nav-link px-2 text-white">TECH SHOP</a></li>
                <li><a href="{% url 'about' %}" class="nav-link px-2 text-white">Про нас</a></li>
                <li><a href="#" class="nav-link px-2 text-white">Корзина</a></li>
                </ul>
        
                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
                </form>
        
                <div class="text-end">
                <button type="button" class="btn btn-outline-light me-2">Увійти</button>
                <button type="button" class="btn btn-warning">Зареєструватися</button>
                </div>
            </div>
            </div>
        </header>
        <div class="container content">
            {% block content %}
                <p>Каталог</p>
            {% endblock %}
        </div>
    </body>
</html>