src/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('about/', views.about, name='about')
]

src/tech_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from tech_shop import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('main.urls', namespace='main')),
    path('', include('goods.urls', namespace='goods')),
    path('api/', include('goods.api.urls', namespace='goods_api')),
    path('users/', include('users.urls', namespace='users')),
    path('carts/', include('carts.urls', namespace='carts')),
    path('api/carts/', include('carts.api.urls', namespace='carts_api')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('api/orders/', include('orders.api.urls', namespace='orders_api')),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
        ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views


app_name = "users"

urlpatterns = [
    path("register/", views.register_user, name="register"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name='users/password_reset.html',
            success_url=reverse_lazy("users:password_reset_done"),
            email_template_name="users/password_reset_email.html",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done",
        auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy("users:password_reset_complete")
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done",
        auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name="password_reset_complete",
    ),
]

src/orders/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from users.models import User
from goods.models import Product


class OrderQuerySet(models.QuerySet):
    def total_price(self):
        return sum(product.product_price for product in self)

    def total_quantity(self):
        return sum(product.quantity for product in self)


class Order(models.Model):
    delivery_methods = (
        ("NP", "Відділення Нової пошти"),
        ("UP", "Відділення Укрпошти"),
        ("CR", "Кур'єрська доставка"),
        ("SD", "Самовивіз зі складу"),
    )
    payment_methods = (
        ("CD", "Оплата при отриманні"),
        ("PP", "Передплата на карту"),
        ("IP", "Розстрочка"),
    )
    statuses = (
        ("OP", "В обробці"),
        ("PP", "Готується до відправлення"),
        ("GT", "Прямує до замовника"),
        ("AR", "Прибуло до відділення"),
        ("WP", "Очікується оплата"),
        ("WS", "Очікує на складі"),
        ("OC", "Відмінено"),
        ("DN", "Виконано"),
    )

    buyer = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name="orders",
        blank=True,
        null=True,
        verbose_name="Акаунт покупця",
    )
    first_name = models.CharField(max_length=150, verbose_name="Ім'я")
    last_name = models.CharField(max_length=150, verbose_name="Прізвище")
    email = models.EmailField(blank=True, null=True, verbose_name="Ел. пошта")
    phone_number = PhoneNumberField(region="UA", verbose_name="Номер телефону")
    delivery_method = models.CharField(
        max_length=2, choices=delivery_methods, verbose_name="Спосіб доставки"
    )
    delivery_address = models.CharField(
        max_length=400, blank=True, null=True, verbose_name="Адреса доставки"
    )
    payment_method = models.CharField(
        max_length=2, choices=payment_methods, verbose_name="Спосіб оплати"
    )
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    extra_comment = models.TextField(
        blank=True, null=True, verbose_name="Коментар до замовлення"
    )
    status = models.CharField(
        max_length=2, choices=statuses, default='OP', blank=True, verbose_name="Статус замовлення"
    )
    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата і час замовлення"
    )

    class Meta:
        ordering = ("-created",)
        verbose_name = "Замовлення"
        verbose_name_plural = "Замовлення"

    def __str__(self):
        return f"Замовлення №{self.pk} | Замовник: {self.last_name} {self.first_name}"


class OrderedProduct(models.Model):
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, related_name="goods", verbose_name="Замовлення"
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="goods",
        verbose_name="Товар",
    )
    name = models.CharField(max_length=150, verbose_name="Назва товару")
    quantity = models.PositiveSmallIntegerField(default=1, verbose_name="Кількість")
    price = models.DecimalField(
        max_digits=7, decimal_places=2, verbose_name="Ціна товару"
    )

    class Meta:
        ordering = ("order",)
        verbose_name = "Замовлений товар"
        verbose_name_plural = "Замовлені товари"

    objects = OrderQuerySet().as_manager()

    def __str__(self):
        return f"Замовлення №{self.order.pk} | замовлено {self.name} в кількості {self.quantity}"

    @property
    def product_price(self):
        return round(self.price * self.quantity, 2)

src/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField


class User(AbstractUser):
    email = models.EmailField(unique=True)
    image = models.ImageField(upload_to='users', blank=True, null=True, verbose_name='Фото')
    birth_date = models.DateField(blank=True, null=True, verbose_name='Дата народження')
    phone_number = PhoneNumberField(region="UA", blank=True, null=True, verbose_name='Номер телефону')

    class Meta:
        verbose_name = 'Користувач'
        verbose_name_plural = 'Користувачі'

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

src/users/forms.py
from enum import unique
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from .models import User


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'phone_number', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    class Meta:
        model = User


class UpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['image', 'first_name', 'last_name', 'email', 'phone_number']

src/users/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from carts.models import Cart
from carts.utils import get_user_carts
from .forms import RegistrationForm, LoginForm, UpdateForm


def register_user(request):
    if request.method == "POST":
        form = RegistrationForm(data=request.POST)

        session_key = request.session.session_key

        if form.is_valid():
            user = form.save(commit=False)
            user.username = form.cleaned_data["email"]
            user.save()
            login(request, user)

            session_carts = Cart.objects.filter(session_key=session_key)
            if session_carts.exists():
                user_carts = get_user_carts(request)
                for cart in session_carts:
                    existed_product = user_carts.filter(product=cart.product)
                    if existed_product.exists():
                        existed_product = existed_product.first()
                        existed_product.quantity += cart.quantity
                        existed_product.save()
                        cart.delete()
                    else:
                        cart.owner = request.user
                        cart.session_key = None
                        cart.save()

            messages.success(request, "Ви успішно створили новий аккаунт")
            return redirect(to="goods:index")
        else:
            return render(request, "users/registration.html", {'form': form}, status=422)
    else:
        form = RegistrationForm()
    context = {"form": form}
    return render(request, "users/registration.html", context)


def login_user(request):
    if request.method == "POST":
        form = LoginForm(data=request.POST)
        username = request.POST.get("username", None)
        password = request.POST.get("password", None)

        session_key = request.session.session_key

        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)

            session_carts = Cart.objects.filter(session_key=session_key)
            if session_carts:
                user_carts = get_user_carts(request)
                for cart in session_carts:
                    existed_product = user_carts.filter(product=cart.product)
                    if existed_product.exists():
                        existed_product = existed_product.first()
                        existed_product.quantity += cart.quantity
                        existed_product.save()
                        cart.delete()
                    else:
                        cart.owner = request.user
                        cart.session_key = None
                        cart.save()

            messages.success(request, "Успішний вхід в аккаунт")
            next_page = request.POST.get("next", None)
            if next_page:
                return redirect(next_page)
            return redirect(to="goods:index")
    else:
        form = LoginForm()
    context = {"form": form}
    return render(request, "users/login.html", context)


def logout_user(request):
    if request.user.is_authenticated:
        logout(request)
        messages.success(request, "Успішний вихід із аккаунту")
    return redirect(to="goods:index")


@login_required(login_url="users:login")
def profile(request):
    return render(request, "users/profile.html")


@login_required(login_url="users:login")
def edit_profile(request):
    if request.method == "POST":
        form = UpdateForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = form.cleaned_data["email"]
            user.save()
            messages.success(request, "Успішна зміна даних профілю")
            return redirect("users:profile")
    else:
        form = UpdateForm()

    context = {"form": form}
    return render(request, "users/edit_profile.html", context)

src/templates/users/edit_profile.html
{% extends "users/profile.html" %}
{% load static %}

{% block profile %}
<form method='post' enctype="multipart/form-data">
    {% csrf_token %}
    {% include "includes/form_errors.html" %}
    <p>
        {% if user.image %}
        <img src="{{ user.image.url }}" alt="{{ user.first_name }} photo" class='profile-pic'>
        {% else %}
        <img src="{% static 'users/default-avatar-profile.jpg' %}" alt="default profile pic" class='profile-pic'>
        {% endif %}
    </p>
    <p>
        <label for="id_image"><span class="profile-label">Фото:</span><br></label>
        <input type="file" name='image' id='id_image' class='form-control' value='{{ user.image }}'>
    </p>
    <p>
        <label for="id_first_name"><span class="profile-label">Ім'я:</span><br></label>
        <input type="text" name='first_name' id='id_first_name' class='form-control' value='{% if request.POST.first_name %}{{ request.POST.first_name }}{% else %}{{ user.first_name }}{% endif %}'>
    </p>
    <p>
        <label for="id_last_name"><span class="profile-label">Прізвище:</span><br></label>
        <input type="text" name='last_name' id='id_last_name' class='form-control' value='{% if request.POST.last_name %}{{ request.POST.last_name }}{% else %}{{ user.last_name }}{% endif %}'>
    </p>
    <p>
        <label for="id_email"><span class="profile-label">Ел. пошта:</span><br></label>
        <input type="email" name='email' id='id_email' class='form-control' value='{% if request.POST.email %}{{ request.POST.email }}{% else %}{{ user.email }}{% endif %}'>
    </p>
    <p>
        <label for="id_phone_number"><span class="profile-label">Номер телефону:</span><br></label>
        <input type="text" name='phone_number' id='id_phone_number' class='form-control' value='{% if request.POST.phone_number %}{{ request.POST.phone_number }}{% else %}{{ user.phone_number }}{% endif %}'>
    </p>
    <div class="row" style='margin-top: 20px;'>
        <div class="col-5">
            <input type="submit" value='Зберегти' class='btn btn-success' style='width: 100%;'>
        </div>
        <div class="col-5 cancel-block">
            <a href="{% url 'users:profile' %}" class='link-hover'>Скасувати</a>
        </div>
    </div>
</form>
{% endblock  %}

src/templates/users/login.html
{% extends 'base.html' %}

{% block title %}
    TECH SHOP - Авторизація
{% endblock  %}

{% block content %}
<div class="row justify-content-center">
    <form method="post" class='col-sm-12 col-md-6'>
        {% csrf_token %}
        {% if form.non_field_errors %}
        <div class="message-container">
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger alert-dismissible message" role="alert">
                    {{ error|striptags }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        </div>
    {% endif %}
        <p>
            <label for="id_username">Ел. пошта:</label>
            <input type="text" name='username', id='id_username' class='form-control' value='{% if form.username.value %}{{ form.username.value }}{% endif %}' required>
        </p>
        <p>
            <label for="id_password">Пароль:</label>
            <input type="password" name='password' id='id_password' class='form-control' value='{% if form.password.value %}{{ form.password.value }}{% endif %}' required>
        </p>
        {% if request.GET.next %}
            <input type="hidden" name='next' value='{{ request.GET.next }}'>
        {% endif %}
        <input type="submit" value="Увійти" class='form-control btn btn-primary'>
        <a href="{% url "users:password_reset" %}" class='link-hover' style='width: fit-content;'>Забули пароль?</a>
    </form>
</div>
{% endblock  %}

src/templates/users/password_reset.html
{% extends "base.html" %}

{% block title %}
    TECH SHOP - Відновлення пароля
{% endblock  %}

{% block content %}
<div class="row align-items-center" style='min-height: 100%;'>
    <div class="col-12 col-md-6" style='margin: 0 auto;'>
        {% block pass_reset_content %}
            <h3>Відновити пароль</h3>
            <p>Для відновлення пароля введіть свій e-mail, який ви вказали при реєстрації і ми надішлемо туди посилання із подальшими вказівками.</p>
            <form method='post'>
                {% include "includes/form_errors.html" %}
                {% csrf_token %}
                <label for="id_email">Ел. пошта:</label>
                <input type="email" class='form-control' id='id_email' name='email' {% if request.POST.email %}value='{{ request.POST.email }}'{% endif %} required>
                <input type="submit" class='btn btn-success' style='margin: 10px 0; width: 100%;' value='Надіслати листа'>
            </form>
        {% endblock  %}
    </div>
</div>
{% endblock  %}

src/templates/users/password_reset_complete.html
{% extends "users/password_reset.html" %}

{% block pass_reset_content %}
    <h3>Пароль було успішно змінено! Тепер ви можете використовувати його для входу.</h3>
    <a href="{% url "users:login" %}" class='btn btn-success'>Увійти в акаунт</a>
{% endblock  %}

src/templates/users/password_reset_confirm.html
{% extends "users/password_reset.html" %}

{% block pass_reset_content %}
    <form method='post'>
        <h3>Встановити новий пароль</h3>
        <p>Введіть ваш новий пароль в відповідні поля.</p>
        <form method='post'>
            {% include "includes/form_errors.html" %}
            {% csrf_token %}
            <label for="id_new_password1">Новий пароль:</label>
            <input type="password" name='new_password1' id='id_new_password1' class='form-control' {% if request.POST.new_password1 %}value='{{ request.POST.new_password1 }}'{% endif %} required>
            <label for="id_new_password2">Новий пароль ще раз:</label>
            <input type="password" name='new_password2' id='id_new_password2' class='form-control' {% if request.POST.new_password2 %}value='{{ request.POST.new_password2 }}'{% endif %} required>
            <input type="submit" class='btn btn-success' style='margin: 10px 0; width: 100%;' value='Встановити новий пароль'>
        </form>
    </form>
{% endblock  %}

src/templates/users/password_reset_done.html
{% extends "users/password_reset.html" %}

{% block pass_reset_content %}
    <h3>На вашу пошту було надіслано посилання для відновлення пароля</h3>
{% endblock  %}

src/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

src/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% load orders_tags %}

{% block title %}
    TECH SHOP - Профіль
{% endblock  %}

{% block cart_nav %}
{% endblock  %}

{% block cart_modal %}
{% endblock  %}


{% block content %}
<div class="row justify-content-center">
    <div class="col-12 col-lg-5" style="margin-bottom: 32px;">
        {% block profile %}
        <div class="profile-info">
                {% if user.image %}
                <img src="{{ user.image.url }}" alt="{{ user.first_name }} photo" class='profile-pic'>
                {% else %}
                <img src="{% static 'users/default-avatar-profile.jpg' %}" alt="default profile pic" class='profile-pic'>
                {% endif %}
            <p>
                <span class="profile-label">Ім'я:</span><br>
                {{ user.first_name }}
            </p>
            <p>
                <span class="profile-label">Прізвище:</span><br>
                {{ user.last_name }}
            </p>
            <p>
                <span class="profile-label">Ел. пошта:</span><br>
                {{ user.email }}
            </p>
            <p>
                <span class="profile-label">Номер телефону:</span><br>
                {{ user.phone_number }}
            </p>
        </div>
            <a href="{% url "users:edit_profile" %}" class="btn btn-primary" style="width: 100%;">Редагувати профіль</a>
        {% endblock  %}
    </div>
    <div class="col-12 col-lg-7">
        <h3 style="padding-left: 15px;">Кошик</h3>
        <div id="cart-items-container">
            {% include 'carts/includes/cart.html' %}
        </div>
    </div>
    <div class="col-12 col-md-9 mt-3">
        <h3 style="padding-left: 15px;">Історія замовлень</h3>
        <div class="accordion" id="accordionPanelsStayOpenExample">
            {% get_user_orders user as orders %}
            {% for order in orders %}
            <div class="accordion-item">
              <h2 class="accordion-header">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" style='display: flex; align-items: center;'
                data-bs-target="#panelsStayOpen-collapse{{ order.id }}" aria-expanded="false" aria-controls="panelsStayOpen-collapse{{ order.id }}">
                <div class="order-status" style='background-color: 
                {% if order.status == 'DN' %}green{% elif order.status == 'OC' %}red{% elif order.status == 'WS' or order.status == 'WP' or order.status == 'AR' %}orange
                {% else %}#4da9ff{% endif %};'></div>
                <div>
                    №{{ order.id }} від {{ order.created }} <br>
                    {{ order.get_status_display }}
                </div>
                </button>
              </h2>
              <div id="panelsStayOpen-collapse{{ order.id }}" class="accordion-collapse collapse">
                <div class="accordion-body row">
                    <div class="col-12 col-md-5">
                        <p>
                            <span class='hint'>Інформація про замовлення</span> <br>
                            {{ order.get_delivery_method_display }} <br>
                            {{ order.get_delivery_address_display }}
                        </p>
                        <p>
                            <span class='hint'>Інформація про отримувача</span> <br>
                            {{ order.last_name }} {{ order.first_name }} <br>
                            {{ order.phone_number }} <br>
                            {{ order.email }}
                        </p>
                    </div>
                    <div class="col-12 col-md-7">
                        <span class='hint' style='display: block; margin-bottom: 10px;'>Товари</span>
                        {% for product in order.goods.all %}
                        <div class="row">
                            <div class="col-12 col-xl-6">
                                <img src="{{ product.product.photo.url }}" alt="{{ product.name }}" style='width: 50px;'>
                                <a href="{{ product.product.get_absolute_url }}" class='link-hover' style='margin: 5px;'>
                                    {{ product.name }}
                                </a>
                            </div>
                            <div class="col-12 col-xl-6 row">
                                <div class='ordered-product-detail col'>
                                    <span class='hint-detail'>Ціна</span>
                                    <span class='ordered-product-text'>{{ product.price }} ₴</span>
                                </div>
                                <div class="ordered-product-detail col">
                                    <span class='hint-detail'>Кількість</span>
                                    <span class='ordered-product-text'>{{ product.quantity }}</span>
                                </div>
                                <div class="ordered-product-detail col" style='display: flex;'>
                                    <span class='hint-detail'>Сума</span>
                                    <span class='ordered-product-text'>{{ product.product_price }} ₴</span>
                                </div>
                            </div>
                        </div>
                        <hr>
                        {% endfor %}
                        <p class='order-info'>
                            <span class='hint'>Оплата {% if order.is_paid %}(Оплачено){% endif %}</span> {{ order.get_payment_method_display }}
                        </p>
                        <p class='order-info'>
                            <span class='hint'>Разом</span> {{ order.goods.total_price }} грн.
                        </p>

                    </div>
                </div>
              </div>
            </div>
            {% empty %}
            <p>Ви ще не робили жодного замовлення</p>
            {% endfor %} 
        </div>      
    </div>
</div>
{% endblock  %}

src/templates/users/registration.html
{% extends 'base.html' %}
{% load users_tags %}

{% block title %}
    TECH SHOP - Реєстрація
{% endblock  %}

{% block content %}
<div class="row justify-content-center">
    <form method="post" class='col-sm-12 col-md-6'>
        {% csrf_token %}
        {% if form.errors %}
        {% get_user_errors form as errors %}
        <div class="message-container">
            {% for error in errors %}
                <div class="alert alert-danger alert-dismissible message" role="alert">
                    {{ error|striptags }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        </div>
        {% endif %}
        <p>
            <label for="id_username">Ім'я:</label>
            <input type="text" name='first_name', id='id_first_name' class='form-control' value='{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}' required>
        </p>
        <p>
            <label for="id_last_name">Прізвище:</label>
            <input type="text" name='last_name', id='id_last_name' class='form-control' value='{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}' required>
        </p>
        <p>
            <label for="id_email">Ел. пошта:</label>
            <input type="email" name='email', id='id_email' class='form-control' value='{% if form.email.value %}{{ form.email.value }}{% endif %}' required>
        </p>
        <p>
            <label for="id_phone_number">Номер телефону:</label>
            <input type="text" name='phone_number', id='id_phone_number' class='form-control' value='{% if form.phone_number.value %}{{ form.phone_number.value }}{% endif %}' required>
        </p>
        <p>
            <label for="id_password1">Пароль:</label>
            <input type="password" name='password1' id='id_password1' class='form-control' value='{% if form.password1.value %}{{ form.password1.value }}{% endif %}' required>
        </p>
        <p>
            <label for="id_password2">Пароль ще раз:</label>
            <input type="password" name='password2' id='id_password2' class='form-control' value='{% if form.password2.value %}{{ form.password2.value }}{% endif %}' required>
        </p>
        <input type="submit" value="Зареєструватися" class='form-control btn btn-primary'>
    </form>
</div>
{% endblock  %}