src/goods/urls.py
from django.urls import path, include
from . import views

app_name = 'goods'

urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:cat_slug>/', views.index, name='view_category'),
    path('product/<slug:slug>/', views.product_details, name='product_details'),
]

src/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('about/', views.about, name='about')
]

src/orders/api/urls.py
from django.urls import path
from . import viewsets


app_name = 'api_orders'

urlpatterns = [
    path('', viewsets.OrderAPI.as_view()),
]

src/orders/urls.py
from django.urls import path

from . import views
from .webhooks import stripe_webhook


app_name = 'orders'

urlpatterns = [
    path('create-order/', views.create_order, name='create_order'),
    path('payment-success/<int:order_id>/', views.payment_success, name='payment_success'),
    path('payment-fail/<int:order_id>/', views.payment_fail, name='payment_fail'),
    path('stripe-webhook/', stripe_webhook, name='stripe_webhook'),
]

src/tech_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from tech_shop import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('main.urls', namespace='main')),
    path('', include('goods.urls', namespace='goods')),
    path('api/', include('goods.api.urls', namespace='goods_api')),
    path('users/', include('users.urls', namespace='users')),
    path('carts/', include('carts.urls', namespace='carts')),
    path('api/carts/', include('carts.api.urls', namespace='carts_api')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('api/orders/', include('orders.api.urls', namespace='orders_api')),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
        ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views


app_name = "users"

urlpatterns = [
    path("register/", views.register_user, name="register"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name='users/password_reset.html',
            success_url=reverse_lazy("users:password_reset_done"),
            email_template_name="users/password_reset_email.html",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done",
        auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy("users:password_reset_complete")
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done",
        auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name="password_reset_complete",
    ),
]

src/orders/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from users.models import User
from goods.models import Product


class OrderQuerySet(models.QuerySet):
    def total_price(self):
        return sum(product.product_price for product in self)

    def total_quantity(self):
        return sum(product.quantity for product in self)


class Order(models.Model):
    delivery_methods = (
        ("NP", "Відділення Нової пошти"),
        ("UP", "Відділення Укрпошти"),
        ("CR", "Кур'єрська доставка"),
        ("SD", "Самовивіз зі складу"),
    )
    payment_methods = (
        ("CD", "Оплата при отриманні"),
        ("PP", "Передплата на карту"),
        ("IP", "Розстрочка"),
    )
    statuses = (
        ("OP", "В обробці"),
        ("PP", "Готується до відправлення"),
        ("GT", "Прямує до замовника"),
        ("AR", "Прибуло до відділення"),
        ("WP", "Очікується оплата"),
        ("WS", "Очікує на складі"),
        ("OC", "Відмінено"),
        ("DN", "Виконано"),
    )

    buyer = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name="orders",
        blank=True,
        null=True,
        verbose_name="Акаунт покупця",
    )
    first_name = models.CharField(max_length=150, verbose_name="Ім'я")
    last_name = models.CharField(max_length=150, verbose_name="Прізвище")
    email = models.EmailField(blank=True, null=True, verbose_name="Ел. пошта")
    phone_number = PhoneNumberField(region="UA", verbose_name="Номер телефону")
    delivery_method = models.CharField(
        max_length=2, choices=delivery_methods, verbose_name="Спосіб доставки"
    )
    delivery_address = models.CharField(
        max_length=400, blank=True, null=True, verbose_name="Адреса доставки"
    )
    payment_method = models.CharField(
        max_length=2, choices=payment_methods, verbose_name="Спосіб оплати"
    )
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    extra_comment = models.TextField(
        blank=True, null=True, verbose_name="Коментар до замовлення"
    )
    status = models.CharField(
        max_length=2, choices=statuses, default='OP', blank=True, verbose_name="Статус замовлення"
    )
    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата і час замовлення"
    )

    class Meta:
        ordering = ("-created",)
        verbose_name = "Замовлення"
        verbose_name_plural = "Замовлення"

    def __str__(self):
        return f"Замовлення №{self.pk} | Замовник: {self.last_name} {self.first_name}"


class OrderedProduct(models.Model):
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, related_name="goods", verbose_name="Замовлення"
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="goods",
        verbose_name="Товар",
    )
    name = models.CharField(max_length=150, verbose_name="Назва товару")
    quantity = models.PositiveSmallIntegerField(default=1, verbose_name="Кількість")
    price = models.DecimalField(
        max_digits=7, decimal_places=2, verbose_name="Ціна товару"
    )

    class Meta:
        ordering = ("order",)
        verbose_name = "Замовлений товар"
        verbose_name_plural = "Замовлені товари"

    objects = OrderQuerySet().as_manager()

    def __str__(self):
        return f"Замовлення №{self.order.pk} | замовлено {self.name} в кількості {self.quantity}"

    @property
    def product_price(self):
        return round(self.price * self.quantity, 2)

src/orders/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = (
            'first_name',
            'last_name',
            'phone_number',
            'email',
            'delivery_method',
            'delivery_address',
            'payment_method',
            'extra_comment',
        )

src/orders/views.py
from decimal import Decimal
import stripe

from django.db import transaction
from django.forms import ValidationError
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.conf import settings
from django.urls import reverse

from carts.utils import get_user_carts

from .models import Order, OrderedProduct
from .forms import OrderForm
from . import tasks


def create_order(request):
    if request.method == "POST":
        form = OrderForm(request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    order = form.save(commit=False)
                    if request.user.is_authenticated:
                        order.buyer = request.user
                    order.save()

                    carts = get_user_carts(request)
                    for cart in carts:
                        if cart.quantity > cart.product.storage_quantity:
                            raise ValidationError(
                               f"В наявності є лише {cart.product.storage_quantity} одиниць товару {cart.product.name}, а ви хочете замовити {cart.quantity}"
                            )
                        OrderedProduct.objects.create(
                            order=order,
                            product=cart.product,
                            name=cart.product.name,
                            quantity=cart.quantity,
                            price=cart.product.sell_price,
                        )
                        cart.product.storage_quantity -= cart.quantity
                        cart.product.save()
                    carts.delete()
            except ValidationError as e:
                messages.error(request, e.args[0])
                return redirect(request.META["HTTP_REFERER"])

            if order.payment_method == 'PP':
                stripe.api_key = settings.STRIPE_SECRET_KEY
                session_data = {
                    'mode': 'payment',
                    'success_url': request.build_absolute_uri(reverse('orders:payment_success', kwargs={'order_id': order.pk})),
                    'cancel_url': request.build_absolute_uri(reverse('orders:payment_fail', kwargs={'order_id': order.pk})),
                    'line_items': [],
                    'client_reference_id': order.id
                }

                order_products = OrderedProduct.objects.filter(order=order)
                for product in order_products:
                    session_data['line_items'].append({
                        'price_data': {
                            'unit_amount': int(product.price) * Decimal(100),
                            'currency': 'uah',
                            'product_data': {
                                'name': product.name
                            }
                        },
                        'quantity': product.quantity
                    })

                session = stripe.checkout.Session.create(**session_data)
                return redirect(session.url, code=303)
            messages.success(request, "Замовлення успішно оформлено")
            tasks.send_successful_order_mail.delay(order.id)
            if request.user.is_authenticated:
                return redirect("users:profile")
            else:
                return redirect("goods:index")

    else:
        if request.user.is_authenticated:
            user_details = {
                "first_name": request.user.first_name,
                "last_name": request.user.last_name,
                "phone_number": request.user.phone_number,
                "email": request.user.email,
            }
            form = OrderForm(initial=user_details)
        else:
            form = OrderForm()
    context = {"form": form}
    return render(request, "orders/order_creation.html", context)


def payment_success(request, order_id=None):
    if order_id and Order.objects.filter(id=order_id).exists():
        context = {'order_id': order_id}
    else:
        return redirect('goods:index')
    return render(request, 'orders/payment_success.html', context)


def payment_fail(request, order_id=None):
    if order_id and Order.objects.filter(id=order_id).exists():
        context = {'order_id': order_id}
    else:
        return redirect('goods:index')
    return render(request, 'orders/payment_fail.html', context)

src/templates/orders/order_creation.html
{% extends "base.html" %}
{% load orders_tags %}

{% block title %}
    TECH SHOP - Оформлення замовлення
{% endblock  %}

{% block content %}
    <div class="row justify-content-center">
        <form method='post' class='col-12 col-md-6'>
            {% csrf_token %}
            {% if form.errors %}
                {% get_order_errors form as errors %}
                <div class="message-container">
                    {% for error in errors %}
                        <div class="alert alert-danger alert-dismissible message" role="alert">
                            {{ error|striptags }}
                            <button   button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
            <p>
                <label for="id_first_name" class='required'>Ім'я:</label>
                <input type="text" id='id_first_name' name='first_name' required
                class='form-control' {% if form.first_name.value %} value='{{ form.first_name.value }}' {% endif %}>
            </p>
            <p>
                <label for="id_last_name" class='required'>Прізвище:</label>
                <input type="text" id='id_last_name' name='last_name' required
                class='form-control' {% if form.last_name.value %} value='{{ form.last_name.value }}' {% endif %}>
            </p>
            <p>
                <label for="id_phone_number" class='required'>Номер телефону:</label>
                <input type="text" id='id_phone_number' name='phone_number' required
                class='form-control' {% if form.phone_number.value %} value='{{ form.phone_number.value }}' {% endif %}>
            </p>
            <p>
                <label for="id_email">Ел. пошта:</label>
                <input type="text" id='id_email' name='email'
                class='form-control' {% if form.email.value %} value='{{ form.email.value }}' {% endif %}>
            </p>
            <p>
                <label for="id_delivery_method" class='required'>Спосіб доставки:</label>
                <select name="delivery_method" id="id_delivery_method" class='form-control' required>
                    {% for x, y in form.fields.delivery_method.choices %}
                    <option value="{{ x }}" {% if form.delivery_method.value == x %}selected{% endif %}>
                        {{ y }}
                    </option>
                    {% endfor %}
                </select>
            </p>
            <p>
                <label for="id_delivery_address" class='required'>Адреса доставки:</label>
                <input type='text' name="delivery_address" id="id_delivery_address" 
                class='form-control' {% if form.delivery_address.value %} value='{{ form.delivery_address.value }}' {% endif %}>
            </p>
            <p>
                <label for="id_payment_method" class='required'>Спосіб оплати:</label>
                <select name="payment_method" id="id_payment_method" class='form-control' required>
                    {% for x, y in form.fields.payment_method.choices %}
                    <option value="{{ x }}" {% if form.payment_method.value == x %}selected{% endif %}>
                        {{ y }}
                    </option>
                    {% endfor %}
                </select>
            </p>
            <p>
                <label for="id_extra_comment">Коментар до замовлення:</label>
                <textarea name='extra_comment' id='id_extra_comment' rows="5" 
                class='form-control'>{% if form.extra_comment.value %}{{ form.extra_comment.value }}{% endif %}</textarea>
            </p>
            <input type="submit" value='Підтвердити замовлення' class='btn btn-success' style='width: 100%;'>
        </form>
    </div>
{% endblock  %}

src/templates/orders/payment_fail.html
{% extends "base.html" %}

{% block title %}
TECH SHOP - Помилка при оплаті
{% endblock  %}

{% block content %}
    <div class='row'>
        <div class="col-12 col-md-6" style='margin: 0 auto;'>
            <h3>Відбулася помилка при оплаті замовлення №{{ order_id }}</h3>
            <p>
                {% if user.is_authenticated %}
                Так як оплата не пройшла, ви можете спробувати оплатити ще раз через деякий час, або змінити спосіб оплати в особистому кабінеті.
            </p>
            <a href="{% url "users:profile" %}" class='btn btn-success'>До особистого кабінету</a>
            {% endif %}
        </div>
    </div>
{% endblock  %}

src/templates/orders/payment_success.html
{% extends "base.html" %}

{% block title %}
TECH SHOP - Оплата пройшла успішно
{% endblock  %}

{% block content %}
    <div class='row'>
        <div class="col-12 col-md-6" style='margin: 0 auto;'>
            <h3>Замовлення №{{ order_id }}</h3>
            <p>Оплата пройшла успішно, на вашу пошту було надіслано листа з інформацією по замовленню. 
            {% if user.is_authenticated %}Також ви можете переглядати історію замовлень та слідкувати за їх статусом в 
            <a href="{% url "users:profile" %}" style='text-decoration: underline;'>особистому кабінеті</a>{% endif %}</p>
                
            <a href="{% url "goods:index" %}" class='btn btn-success'>Продовжити покупки</a>
        </div>
    </div>
{% endblock  %}