src/carts/api/urls.py
from django.urls import path
from . import viewsets


app_name = 'api_carts'

urlpatterns = [
    path('', viewsets.CartAPIList.as_view()),
    path('<int:pk>/', viewsets.CartDetailsAPI.as_view()),
]

src/carts/urls.py
from django.urls import path
from . import views


app_name = 'carts'

urlpatterns = [
    path('cart-add/', views.cart_add, name='cart_add'),
    path('cart-delete/', views.cart_delete, name='cart_delete'),
    path('cart-change/', views.cart_change, name='cart_change'),
]

src/goods/urls.py
from django.urls import path, include
from . import views

app_name = 'goods'

urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:cat_slug>/', views.index, name='view_category'),
    path('product/<slug:slug>/', views.product_details, name='product_details'),
]

src/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('about/', views.about, name='about')
]

src/orders/urls.py
from django.urls import path

from . import views
from .webhooks import stripe_webhook


app_name = 'orders'

urlpatterns = [
    path('create-order/', views.create_order, name='create_order'),
    path('payment-success/<int:order_id>/', views.payment_success, name='payment_success'),
    path('payment-fail/<int:order_id>/', views.payment_fail, name='payment_fail'),
    path('stripe-webhook/', stripe_webhook, name='stripe_webhook'),
]

src/tech_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from tech_shop import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('main.urls', namespace='main')),
    path('', include('goods.urls', namespace='goods')),
    path('api/', include('goods.api.urls', namespace='goods_api')),
    path('users/', include('users.urls', namespace='users')),
    path('carts/', include('carts.urls', namespace='carts')),
    path('api/carts/', include('carts.api.urls', namespace='carts_api')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('api/orders/', include('orders.api.urls', namespace='orders_api')),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
        ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/carts/models.py
from django.db import models
from goods.models import Product
from users.models import User


class CartQueryset(models.QuerySet):
    def total_price(self):
        if self:
            return round(sum(cart.product_price for cart in self), 2)
        return 0

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Cart(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cart', blank=True, null=True, verbose_name='Власник')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.PositiveSmallIntegerField(default=1, verbose_name='Кількість')
    session_key = models.CharField(max_length=32, blank=True, null=True, verbose_name='Ключ сесії')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Створено')

    class Meta:
        verbose_name = 'Товар кошика'
        verbose_name_plural = 'Товари кошика'
        ordering = ('owner',)

    objects = CartQueryset().as_manager()

    def __str__(self):
        if self.owner:
            return f'{self.owner.email} wants to buy {self.quantity}x of {self.product.name}'
        return f'session key {self.session_key} wants to buy {self.quantity}x of {self.product.name}'

    @property
    def product_price(self):
        return round(self.product.sell_price * self.quantity, 2)

src/carts/views.py
from django.http import JsonResponse
from django.template.loader import render_to_string
from .models import Cart
from .utils import get_user_carts


def cart_add(request):
    product_id = request.POST.get('product_id')

    if request.user.is_authenticated:
        carts = Cart.objects.filter(owner=request.user, product_id=product_id)
        if carts.exists():
            cart = carts.first()
            cart.quantity += 1
            cart.save()
        else:
            Cart.objects.create(owner=request.user, product_id=product_id)
    else:
        carts = Cart.objects.filter(session_key=request.session.session_key, product_id=product_id)
        if carts.exists():
            cart = carts.first()
            cart.quantity += 1
            cart.save()
        else:
            Cart.objects.create(session_key=request.session.session_key, product_id=product_id)

    context = {'goods': get_user_carts(request)}
    cart_items_html = render_to_string('carts/includes/cart.html', request=request, context=context)
    response_data = {
        'cart_items_html': cart_items_html,
        'message': 'Товар успішно додано до кошика'
    }
    return JsonResponse(response_data)


def cart_delete(request):
    cart_id = request.POST.get('cart_id')

    if request.user.is_authenticated:
        cart = Cart.objects.get(owner=request.user, id=cart_id)
        quantity_deleted = cart.quantity
        cart.delete()
    else:
        cart = Cart.objects.get(session_key=request.session.session_key, id=cart_id)
        quantity_deleted = cart.quantity
        cart.delete()

    context = {'goods': get_user_carts(request)}
    cart_items_html = render_to_string('carts/includes/cart.html', request=request, context=context)
    response_data = {
        'quantity_deleted': quantity_deleted,
        'cart_items_html': cart_items_html
    }
    return JsonResponse(response_data)


def cart_change(request):
    cart_id = request.POST.get('cart_id')
    quantity = request.POST.get('quantity')

    cart = Cart.objects.get(id=cart_id)
    cart.quantity = quantity
    cart.save()

    context = {'goods': get_user_carts(request)}
    cart_items_html = render_to_string('carts/includes/cart.html', request=request, context=context)
    response_data = {
        'cart_items_html': cart_items_html
    }
    return JsonResponse(response_data)

src/templates/carts/includes/cart.html
{% load static %}
{% load carts_tags %}

{% if goods %}
    {% for cart_item in goods %}
    <div style='display: flex; align-items: center; margin: 10px 0;'>
        <div style='width: 80px; margin-right: 20px;'>
                {% if cart_item.product.photo %}
                <img src="{{ cart_item.product.photo.url }}" alt="{{ cart_item.product.name }}">
                {% else %}
                <img src="{% static 'goods/No-image-found.jpg' %}" alt="">
                {% endif %}
        </div>
        <div class='row' style='flex-grow: 1;'>
            <div class="col-7" style='display: flex; flex-direction: column;'>
                <div class="">
                    <a href="{% url "goods:product_details" cart_item.product.slug %}" class='link-hover'>
                        <b>{{ cart_item.product.name }}</b>
                    </a>
                </div>
                <div class='input-group'>
                    <button class="btn decrement" data-cart-change-url="{% url "carts:cart_change" %}" data-cart-id="{{ cart_item.id }}">
                        {% csrf_token %}
                        -
                    </button>
                        <input type="text" class='form-control number' value="{{ cart_item.quantity }}" style='margin: 0 10px;'>
                    <button class="btn increment" data-cart-change-url="{% url "carts:cart_change" %}" data-cart-id="{{ cart_item.id }}">
                        {% csrf_token %}
                        +
                    </button>
                </div>
            </div>
            <div class="col-5" style='display: flex; justify-content: center; align-items: center;'>
                <span>{{ cart_item.product_price }} ₴</span>
            </div>
        </div>
        <div style='width: 27px; margin-left: 20px;'>
            <a href="{% url "carts:cart_delete" %}" class='remove-from-cart' data-cart-id="{{ cart_item.id }}">
                {% csrf_token %}
                <img src="{% static "carts/rubbish-bin.svg" %}" alt="delete product">
            </a>
        </div>
    </div>
    {% endfor %}
    <div>
        <h5>Всього {{ goods.total_quantity }} товарів на суму {{ goods.total_price }} грн.</h5>
        <a href="{% url "orders:create_order" %}" class='btn btn-success'>Оформити замовлення</a>
    </div>
{% else %}
    <p>В кошику порожньо</p>
    <a href="{% url "goods:index" %}" class='btn btn-success'>Розпочати покупки</a>
{% endif %}